# Generated by Django 4.2.3 on 2023-07-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('write', models.CharField(max_length=100)),
                ('send', models.CharField(max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('contents', models.TextField(blank=True)),
            ],
        ),
    ]
